"use client";

import { useState } from "react";
import { Copy, Download, Plus, Save, Trash2 } from "lucide-react";
import { WaterfallBars } from "@/components/charts/analytics-charts";
import { Badge, Kpi, PageHeading, Section } from "@/components/ui/primitives";
import { calculateShouldCost } from "@/domain/procurement/should-cost";
import { downloadBlob, formatInr, formatNumber, formatPercent } from "@/lib/format";
import { useWorkspace } from "@/stores/workspace-store";
import type { ShouldCostModel, ShouldCostOperation } from "@/types/procurement";

const numberValue = (value: string) => Number.isFinite(Number(value)) ? Number(value) : 0;

export function ShouldCostModule() {
  const workspace = useWorkspace();
  const [model, setModel] = useState<ShouldCostModel>(() => structuredClone(workspace.savedShouldCostModels[0]!));
  const result = calculateShouldCost(model);
  const update = <K extends keyof ShouldCostModel>(key: K, value: ShouldCostModel[K]) => setModel((current) => ({ ...current, [key]: value, updatedAt: new Date().toISOString() }));
  const updateOperation = (id: string, key: keyof ShouldCostOperation, value: string | number) => setModel((current) => ({ ...current, operations: current.operations.map((operation) => operation.id === id ? { ...operation, [key]: typeof operation[key] === "number" ? numberValue(String(value)) : value } : operation), updatedAt: new Date().toISOString() }));
  const addOperation = () => setModel((current) => ({ ...current, operations: [...current.operations, { id: `OP-${Date.now()}`, name: "New operation", cycleTimeMinutes: 1, setupTimeMinutes: 10, batchSize: 100, machineHourlyRate: 500, labourHourlyRate: 180, toolingPerPart: 2, utilitiesPerPart: 1 }] }));
  const duplicate = () => { const copy = { ...structuredClone(model), id: `SCM-${Date.now()}`, name: `${model.name} copy`, updatedAt: new Date().toISOString() }; workspace.saveShouldCostModel(copy); setModel(copy); };
  const exportModel = () => downloadBlob(`${model.name.toLowerCase().replaceAll(" ", "-")}-should-cost.json`, JSON.stringify({ model, result }, null, 2), "application/json");

  return (
    <>
      <PageHeading eyebrow="Model" title="Should-cost engine" description="Build a defensible manufactured-part cost from material yield, operation time, resources, overhead, logistics and supplier margin." actions={<><button className="button button-secondary button-small" onClick={exportModel}><Download size={14} />Export model</button><button className="button button-primary button-small" onClick={() => workspace.saveShouldCostModel(model)}><Save size={14} />Save locally</button></>} />
      <div className="model-tabs" role="tablist" aria-label="Saved should-cost models">{workspace.savedShouldCostModels.map((saved) => <button role="tab" aria-selected={model.id === saved.id} className={model.id === saved.id ? "active" : ""} key={saved.id} onClick={() => setModel(structuredClone(saved))}><span>{saved.name}</span><small>{formatInr(calculateShouldCost(saved).target, false)} target</small></button>)}<button className="model-add" onClick={duplicate}><Plus size={14} />Duplicate</button></div>
      <div className="kpi-grid">
        <Kpi label="Modelled range" value={`${formatInr(result.low, false)} – ${formatInr(result.high, false)}`} note="Controlled sensitivity: −6% / +8%" />
        <Kpi label="Target should-cost" value={formatInr(result.target, false)} note={`${formatInr(result.material, false)} net material`} tone="positive" />
        <Kpi label="Supplier quotation" value={formatInr(model.supplierQuote, false)} note={`${formatPercent(result.quoteGapPercent)} above target`} tone={result.quoteGap > 0 ? "warning" : "positive"} />
        <Kpi label="Negotiation opportunity" value={formatInr(result.annualOpportunity)} note={`${formatNumber(model.annualQuantity)} annual units`} tone="positive" />
      </div>
      <div className="workspace-grid should-cost-layout">
        <Section className="span-7" title="Cost model assumptions" description="All inputs are editable and recalculate immediately">
          <div className="form-section"><h3>Part and raw material</h3><div className="form-grid form-grid-3"><div className="field"><label htmlFor="sc-name">Model name</label><input id="sc-name" value={model.name} onChange={(event) => update("name", event.target.value)} /></div><div className="field"><label htmlFor="sc-material">Material</label><input id="sc-material" value={model.material} onChange={(event) => update("material", event.target.value)} /></div><div className="field"><label htmlFor="sc-rate">Raw material rate (₹/kg)</label><input id="sc-rate" type="number" min="0" value={model.rawMaterialRate} onChange={(event) => update("rawMaterialRate", numberValue(event.target.value))} /></div><div className="field"><label htmlFor="sc-gross">Gross weight (kg)</label><input id="sc-gross" type="number" min="0" step="0.01" value={model.grossWeight} onChange={(event) => update("grossWeight", numberValue(event.target.value))} /></div><div className="field"><label htmlFor="sc-finished">Finished weight (kg)</label><input id="sc-finished" type="number" min="0" step="0.01" value={model.finishedWeight} onChange={(event) => update("finishedWeight", numberValue(event.target.value))} /></div><div className="field"><label htmlFor="sc-scrap">Scrap recovery (₹/kg)</label><input id="sc-scrap" type="number" min="0" value={model.scrapRecoveryRate} onChange={(event) => update("scrapRecoveryRate", numberValue(event.target.value))} /></div></div></div>
          <div className="form-section"><div className="subsection-heading"><h3>Manufacturing operations</h3><button className="button button-small button-secondary" onClick={addOperation}><Plus size={13} />Add operation</button></div><div className="table-scroll"><table className="data-table operation-table"><thead><tr><th>Operation</th><th className="numeric">Cycle min</th><th className="numeric">Setup min</th><th className="numeric">Batch</th><th className="numeric">Machine ₹/h</th><th className="numeric">Labour ₹/h</th><th className="numeric">Tooling</th><th /></tr></thead><tbody>{model.operations.map((operation) => <tr key={operation.id}><td><input aria-label="Operation name" value={operation.name} onChange={(event) => updateOperation(operation.id, "name", event.target.value)} /></td>{(["cycleTimeMinutes", "setupTimeMinutes", "batchSize", "machineHourlyRate", "labourHourlyRate", "toolingPerPart"] as const).map((key) => <td className="numeric" key={key}><input aria-label={`${operation.name} ${key}`} type="number" min="0" value={operation[key]} onChange={(event) => updateOperation(operation.id, key, event.target.value)} /></td>)}<td><button className="table-icon" onClick={() => update("operations", model.operations.filter((item) => item.id !== operation.id))} disabled={model.operations.length === 1} aria-label={`Delete ${operation.name}`}><Trash2 size={13} /></button></td></tr>)}</tbody></table></div></div>
          <div className="form-section"><h3>Commercial assumptions</h3><div className="form-grid form-grid-3"><div className="field"><label htmlFor="sc-overhead">Overhead (%)</label><input id="sc-overhead" type="number" min="0" max="100" step="0.1" value={model.overheadRate * 100} onChange={(event) => update("overheadRate", numberValue(event.target.value) / 100)} /></div><div className="field"><label htmlFor="sc-packaging">Packaging (₹/part)</label><input id="sc-packaging" type="number" min="0" value={model.packaging} onChange={(event) => update("packaging", numberValue(event.target.value))} /></div><div className="field"><label htmlFor="sc-freight">Freight (₹/part)</label><input id="sc-freight" type="number" min="0" value={model.freight} onChange={(event) => update("freight", numberValue(event.target.value))} /></div><div className="field"><label htmlFor="sc-margin">Supplier margin (%)</label><input id="sc-margin" type="number" min="0" max="100" step="0.1" value={model.marginRate * 100} onChange={(event) => update("marginRate", numberValue(event.target.value) / 100)} /></div><div className="field"><label htmlFor="sc-quote">Supplier quote (₹/part)</label><input id="sc-quote" type="number" min="0" value={model.supplierQuote} onChange={(event) => update("supplierQuote", numberValue(event.target.value))} /></div><div className="field"><label htmlFor="sc-annual">Annual quantity</label><input id="sc-annual" type="number" min="0" value={model.annualQuantity} onChange={(event) => update("annualQuantity", numberValue(event.target.value))} /></div></div></div>
        </Section>
        <div className="span-5 stacked-panels">
          <Section title="Should-cost waterfall" description="Per-part modelled cost build-up"><WaterfallBars items={[{ label: "Material", value: result.material }, { label: "Conversion", value: result.conversion }, { label: "Overhead", value: result.overhead }, { label: "Packaging", value: result.packaging }, { label: "Freight", value: result.freight }, { label: "Margin", value: result.margin, tone: "gold" }]} /><div className="should-cost-total"><span>Target should-cost</span><strong>{formatInr(result.target, false)}</strong></div></Section>
          <Section title="Model diagnostics" description="Explainable calculation detail"><ul className="metric-list panel-body"><li><span>Gross material cost</span><strong>{formatInr(result.grossMaterial, false)}</strong></li><li><span>Less: scrap recovery</span><strong>−{formatInr(result.scrapRecovery, false)}</strong></li><li><span>Machine cost</span><strong>{formatInr(result.machine, false)}</strong></li><li><span>Direct labour</span><strong>{formatInr(result.labour, false)}</strong></li><li><span>Setup allocation</span><strong>{formatInr(result.setup, false)}</strong></li><li><span>Tooling + utilities</span><strong>{formatInr(result.tooling + result.utilities, false)}</strong></li></ul></Section>
          <div className="model-actions"><button className="button button-secondary button-small" onClick={duplicate}><Copy size={13} />Duplicate</button><button className="button button-danger button-small" onClick={() => { workspace.deleteShouldCostModel(model.id); const next = workspace.savedShouldCostModels.find((item) => item.id !== model.id); if (next) setModel(structuredClone(next)); }} disabled={workspace.savedShouldCostModels.length <= 1}><Trash2 size={13} />Delete saved model</button></div>
        </div>
      </div>
      <div className="assumption-note"><Badge tone="info">Estimated cost</Badge><p>The range reflects controlled sensitivity, not a supplier quotation. Cycle times, rates, yield, overhead and margin must be validated before commercial use.</p></div>
    </>
  );
}
