import Link from "next/link";
import { AppWindow, ArrowLeft, ArrowRight, Database, Gauge, Server, Sigma } from "lucide-react";
import { Logo } from "@/components/brand/logo";

export const metadata = { title: "Architecture" };

export default function ArchitecturePage() {
  const nodes = [[AppWindow, "Browser", "Next.js interface + local file parsing"], [Server, "Route handlers", "Validated stateless analytical APIs"], [Sigma, "Procurement domain", "Typed formulas and optimization"], [Gauge, "Decision output", "Explainable metrics and recommendations"]] as const;
  return <main className="document-page"><header><Logo /><Link href="/workspace/overview"><ArrowLeft size={14} />Back to workspace</Link></header><article><span className="eyebrow">System design</span><h1>Architecture</h1><p className="document-lead">A single full-stack Next.js application designed for a zero-cost portfolio deployment with no production database or external decision API.</p><div className="architecture-flow">{nodes.map(([Icon, title, copy], index) => <div key={title}><Icon size={23} /><span>{String(index + 1).padStart(2, "0")}</span><strong>{title}</strong><p>{copy}</p>{index < nodes.length - 1 ? <ArrowRight aria-hidden="true" /> : null}</div>)}</div><div className="architecture-local"><Database size={24} /><div><strong>Local workspace · IndexedDB</strong><p>Demo data, imported records, saved scenarios, should-cost models, settings and opportunity statuses persist only in the user’s browser. Workspace JSON provides a portable backup.</p></div></div><div className="architecture-facts"><div><span>Frontend</span><strong>Next.js App Router + React + custom CSS</strong></div><div><span>Backend</span><strong>Next.js Route Handlers + Zod validation</strong></div><div><span>Domain engine</span><strong>Strict TypeScript analytics and simulations</strong></div><div><span>Optimization</span><strong>Deterministic capacity-constrained allocation</strong></div><div><span>External AI API</span><strong>None</strong></div><div><span>Hosted database</span><strong>None</strong></div><div><span>Required secrets</span><strong>None</strong></div><div><span>Remote optimizer</span><strong>None</strong></div></div></article></main>;
}
